FROM node:23-alpine AS builder

WORKDIR /app
COPY package*.json tsconfig.json ./
RUN npm ci

COPY apps/cdms ./apps/cdms
COPY apps/inventory-emulator ./apps/inventory-emulator
RUN npm run build

FROM node:23-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist
COPY apps/cdms/src/db/migrations ./dist/apps/cdms/src/db/migrations

EXPOSE 3000
CMD ["node", "dist/apps/cdms/src/app.js"]
