FROM node:23-alpine AS builder

WORKDIR /app
COPY package*.json tsconfig.json ./
RUN npm ci

COPY apps/inventory-emulator ./apps/inventory-emulator
COPY apps/cdms ./apps/cdms
RUN npm run build

FROM node:23-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 3001
CMD ["node", "dist/apps/inventory-emulator/src/app.js"]
